Remove genomic info from validation command
thehyve/cbioportal-staging pull request #47
Opened 2021-02-26 15:47 UTC by oplantalech

* In accordance with cbioportal/cbioportal#7969 which is merged since version 3.4.17

2021-02-26 16:07 UTC, SRodenburg approved these changes
Looks good

2021-02-26 16:14 UTC, SRodenburg requested changes

2021-02-26 16:14 UTC, SRodenburg commented on src/main/java/org/cbioportal/staging/services/command/DockerCommandBuilder.java
> +            "validateData.py", "-p", "/portalinfo", "-s", "/study", "--html=/outreport.html");
over here you use `--html=/outreport.html`  -- also as one single argument (not sure how the `ProcessBuilder` will handle that).

In the file `LocalCommandBuilder.java` this is done in 2 args:
`"./validateData.py", "-s", studyDirPath, "-p",
            portalInfoPath, "-html", reportFilePath, "-v"`

2021-02-26 16:14 UTC, SRodenburg commented on src/main/java/org/cbioportal/staging/services/command/LocalCommandBuilder.java
>              portalInfoPath, "-html", reportFilePath, "-v");
You should use the same syntax throughout

2021-02-26 16:14 UTC, SRodenburg commented on src/test/resources/local_database/portal.properties
> -species=human
I think these properties are still used as the default values. Can you confirm they are use nowhere?

2021-02-26 16:18 UTC, oplantalech commented on src/test/resources/local_database/portal.properties
> -species=human
I can confirm because the test that uses these properties has passed.

2021-02-26 16:19 UTC, oplantalech commented on src/test/resources/local_database/portal.properties
> -species=human
Also, before the properties were read with a method in utils that it is not used anymore (I kept the code in utils in case we need to parse portal.properties in the future)

2021-02-26 16:19 UTC, SRodenburg requested changes

2021-02-26 16:19 UTC, SRodenburg commented on src/main/java/org/cbioportal/staging/services/command/DockerCommandBuilder.java
> +            "validateData.py", "-p", "/portalinfo", "-s", "/study", "-html=/outreport.html");
split into 2 args
```java
"-html", "/outreport.html"
```

2021-02-26 16:19 UTC, SRodenburg commented on src/main/java/org/cbioportal/staging/services/command/DockerComposeCommandBuilder.java
> +                "-html=" + internalReportFilePath.toString()
split into 2 args

2021-03-01 09:12 UTC, SRodenburg approved these changes

2021-03-01 09:40 UTC, merged